### PR TITLE
fix uninitialized constant InheritedResources::Base (NameError)

### PR DESCRIPTION
**Pull request by mvaragnat**

### CODE REVIEW

**Comment by mvaragnat** [comment]
based on this advice : https://github.com/activeadmin/activeadmin/issues/7196#issuecomment-1132578565

**Comment by ghulamjilani** [comment]
when I have upgrade my rails version 6.1 to 7 then facing the following issue related to activeadmin. Implemented many solutions including Rails.application.config.after_initialize do  but its still through the following error.

`uninitialized constant InheritedResources::Base (NameError)

  class BaseController < ::InheritedResources::Base
                                             ^^^^^^
Did you mean?  Base64
`

**Comment by Ivan-P23994** [comment]
> I upgraded my rails version from 6.1 to 7 but facing the following issue related to activeadmin. I have Implemented many solutions including `Rails.application.config.after_initialize do ` But, still it is throwing this error..
> 
> ```
> uninitialized constant InheritedResources::Base (NameError)
> 
>   class BaseController < ::InheritedResources::Base
>                                              ^^^^^^
> Did you mean?  Base64
> ```

Have you managed to find a workaround? I am encountering the same issue...

**Comment by FlintOFF** [comment]
Same issue

**Comment by rbngzlv** [comment]
I opened a new PR with the changes that worked for me (#25), because with this changes another errors is raised. I added a comment in the PR description with a workaround while we wait for someane to merge the PR.

**Comment by mvaragnat** [comment]
closing in favor of #22 

#22 solves the problems when upgrading to Rails 7

**Pull request closed without merging**
